config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    return unless user.present?

    can :read, :all
    can(%i[create update destroy], Post, user:)
    can(%i[create update destroy], Comment, user:)

    return unless user.is? :admin

    can :manage, :all
  end
end

app/models/application_record.rb
# Application record class
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# Comment model
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :increment_comments_counter
  after_destroy :decrement_comments_counter

  private

  def increment_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
# Like model
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :increment_likes_counter
  after_destroy :decrement_likes_counter

  private

  def increment_likes_counter
    post.increment!(:likes_counter)
  end

  def decrement_likes_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
# Post model
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user

  after_save :increment_posts_counter
  after_destroy :decrement_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def last_five_comments
    comments.limit(5).order(created_at: :desc)
  end

  private

  def increment_posts_counter
    user.increment!(:posts_counter)
  end

  def decrement_posts_counter
    user.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  has_many :comments
  has_many :posts
  has_many :likes

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def last_three_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @comments }
      format.json { render json: @comments }
    end
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      flash[:success] = 'New comment successfully added!'
      respond_to do |format|
        format.html { redirect_to user_post_path user_id: current_user.id, id: @comment.post.id }
        format.xml { render xml: @comment, status: :created }
        format.json { render json: @comment, status: :created }
      end
    else
      flash.now[:error] = 'Comment creation failed'
      respond_to do |format|
        format.html { render :new }
        format.xml { render xml: @comment.errors, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'The comment item was successfully destroyed.'
    redirect_to user_post_path user_id: current_user.id
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user_id = params[:user_id]
    @post_id = params[:post_id]
    @like = Like.new(user: current_user, post: Post.find_by(id: @post_id))
    if @like.save
      flash[:success] = 'New like successfully added!'
      redirect_to "/users/#{@user_id}/posts/#{@post_id}"
    else
      flash.now[:error] = 'Like creation failed'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.where(user_id: params[:user_id]).includes(:comments)
    @user = User.find(params[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @posts }
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @like = Like.new
  end

  def new
    @id = params[:user_id]
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'New post successfully added!'
      redirect_to user_posts_path
    else
      flash.now[:error] = 'Post creation failed'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'The to-do item was successfully destroyed.'
    redirect_to user_posts_path user_id: current_user.id
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).merge(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# Application helper module
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= bootstrap_form_with model: @comment, url: user_post_comments_path, method: :post, local: true do |f| %>

  <%= f.text_area :text %>
  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="post-page">
  <div class="user-cont">
    <div>
      <img src="https://user-images.githubusercontent.com/37116322/222183427-3450696b-429a-4e9a-9e19-48bbe4b48edf.png" alt="profile">
    </div>
    <div class="user-info">
      <h2><%= @user.name %></h2>
      <div>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </div>
  
  <% @posts.each do |post| %>
    <div class="post-cont">
      <h3>Post #<%= post.id %></h3>
      <p><%= post.text %></p>
      <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
      <div class="view-post">
        <%= link_to 'View', "/users/#{@user.id}/posts/#{post.id}" %>
        <% if can? :destroy, post %>
          <%= link_to "Delete", user_post_path(@user.id, post.id), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
        <% end %>
      </div>
    </div>
    <div class="comment-cont">
      <% post.last_five_comments.each do |comment| %>
        <p><%= comment.user.name %>: <%= comment.text %></p>
      <% end %>
    </div>
  <% end %>

  <button>
    <%= link_to "New Post", new_user_post_path, class: 'btn btn-primary' %>
  </button>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= bootstrap_form_with model: @post, url: "/users/#{@id}/posts", method: :post, local: true do |f| %>

  <%= f.text_field :title %>
  <%= f.text_area :text %>
  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<div class="post-show-page">
  <div class="post-cont">
    <div class="post-head">
      <h3>Post #<%= @post.id %> by <%= @post.user.name %></h3>
      <p>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    </div>
    <p><%= @post.text %><p>
  </div>
  <div class="comment-cont">
    <% @post.comments.each do |comment| %>
      <p><%= comment.user.name %>: <%= comment.text %></p>
      <%= bootstrap_form_with model: @like, url: "/users/#{@post.user.id}/posts/#{@post.id}/likes", method: :post, local: true do |f| %>
        <%= f.submit %>
      <% end %>
      <% if can? :destroy, comment %>
          <%= link_to "Delete", user_post_comment_path(@post.user.id, @post.id), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
      <% end %>
    <% end %>
  </div>

  <button>
    <%= link_to "New Comment", "/users/#{@post.user.id}/posts/#{@post.id}/comments/new", class: 'btn btn-primary' %>
  </button>
</div>

app/views/users/index.html.erb
<div class="user-page">
  <%= button_to 'Log out', destroy_user_session_path, method: :delete %>

  <% @users.each do |user| %>
    <div class="user-cont">
      <div>
        <img src="https://user-images.githubusercontent.com/37116322/222183427-3450696b-429a-4e9a-9e19-48bbe4b48edf.png" alt="profile">
      </div>
      <div class="user-info">
        <h2><%= user.name %></h2>
        <div>
          <p>Number of posts: <%= user.posts_counter %></p>
          <%= link_to 'View', "/users/#{user.id}" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show-page">
  <div class="user-cont">
    <div>
      <img src="https://user-images.githubusercontent.com/37116322/222183427-3450696b-429a-4e9a-9e19-48bbe4b48edf.png" alt="profile">
    </div>
    <div class="user-info">
      <h2><%= @user.name %></h2>
      <div>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
  </div>
  <div class="bio-cont">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>
  <% @user.last_three_posts.each do |post| %>
    <div class="post-cont">
      <h3>Post #<%= post.id %></h3>
      <p><%= post.text %></p>
      <span>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
    </div>
  <% end %>

  <button><%= link_to 'See all posts', "/users/#{@user.id}/posts" %></button>
</div>